### ISSUE TITLE
Could not load assembly 'Xamarin.RangeSlider.Droid, Version=0.7.8.0, Culture=neutral, PublicKeyToken='.

### ISSUE THREAD

**Issue by ShahramShobeiri1** [halkar/xamarin-range-slider#94]
Hello

When i try to build my Android project i get this error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.RangeSlider.Droid, Version=0.7.8.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.RangeSlider.Droid.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection``1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Sayba.Xamarin.Android	`

I'm using Xamarin.Forms v2.4.0.282 and Xamarin.Froms.RangeSlider v0.7.8, Xamarin.RangeSlider v0.7.8
My PCL and UWP projects build is OK
Is it related to Xamarin.Android.Support version?

**Comment by halkar** [comment]
@ShahramShobeiri1 do you have a sample project to reproduce the issue?

**Comment by halkar** [comment]
@ShahramShobeiri1 most likely you'll need to update your target SDK to 23+ (Android 6+) and update all Android support libraries.

**Comment by ShahramShobeiri1** [comment]
My SDK is Android 6.0(API 23)
Here is my sample project, I just made a new cross platform app and add Xamarin.Forms.RangeSlider by nuget package manager to PCL, Android and UWP projects. And build error appears again, Should i update my SDK to 25?

**Comment by halkar** [comment]
Thanks @ShahramShobeiri1 I'll check later today. For now you can rollback the package to version 0.6.19.

**Comment by halkar** [comment]
Sorry @ShahramShobeiri1 Wasn't able to download your file yesterday. Something is wrong with my internet connection. Will check it today.

**Comment by ShahramShobeiri1** [comment]
Thanks

**Comment by halkar** [comment]
Fixed in 0.7.10

**Comment by ShahramShobeiri1** [comment]
Thanks, but unfortunately it's not fixed. I have the build error as before. My Xamarin.Android.Support.v4 version is v23.3.0 and i can't update that because Xamarin.Forms 2.4.0.282 is based on Xamarin.Android.Support.v4 23.3.0

**Comment by halkar** [comment]
@ShahramShobeiri1 you should be able to update `Xamarin.Android.Support.v4` as `Xamarin.Forms` supports any version >= `23.3.0`

**Comment by ShahramShobeiri1** [comment]
I like to update but i can't!!!
Here is some description about this https://forums.xamarin.com/discussion/57283/unable-to-find-a-version-of-xf-compatible-with

**Comment by halkar** [comment]
@ShahramShobeiri1 weird. I was able to update everything. Thank!

**Comment by halkar** [comment]
@ShahramShobeiri1 please check out version 0.7.11

**Comment by ShahramShobeiri1** [comment]
Thank you very much. The build is OK now!
